FROM python:3.12-slim AS build

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt update && \
    apt install --no-install-recommends -y libpq-dev gcc && \
    rm -rf var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip && \ 
    pip install --no-cache-dir --prefix=/packages -r requirements.txt


FROM python:3.12-slim 

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY --from=build /packages /usr/local

COPY . .

RUN apt update && \
    apt install --no-install-recommends -y curl && \
    rm -rf var/lib/apt/lists/*

EXPOSE 8000

ENTRYPOINT [ "./entrypoint.sh" ]